### ISSUE TITLE
Create Edit Page

### ISSUE THREAD

**Issue by MattKai45** [KaiserEngineering/shiftlight-configuration-tool#6]
User selects a drop down for the Conig type. For now it is Shift Light or Boost Gauge. But more options can be used in the future. The following are the unique general settings that should be available based on the config type. There are NO shared options in this page. *More settings can be added in the future.

1. Shift Light (CONFIG)
1.1.	Activation Point (ACT) – Numerical Input
1.2.	Shift Point (SHIFT) – Numerical Input
1.3.	Animation (ANIM) – List Box
1.4.	Color Palette (COLOR) – List Box
1.5.	Peak Hold (PEAK) – Checkbox
1.6.	Flash at Shift Point (FLASH) – Checkbox	

2.	Boost Gauge (CONFIG)
2.1.	Minimum (BOOSTMIN) – Numerical Input
2.2.	Maximum (BOOSTMAX) – Numerical Input

**Comment by craigkai** [comment]
This is basically done, there is one bug with the selecting of the config type that needs to be fixed still
